#+SETUPFILE: https://fniessen.github.io/org-html-themes/setup/theme-readtheorg.setup
#+TITLE: Preliminary

* logic
** and
   $\land$
** or
   $\lor$
** imply
   $\to$
** iff
   $\iff$
** not
   $\lnot$
** any
   $\forall$
** exist
   $\exists$

* set and class
** class
   a class is a collection $A$ of objects such that given any object $x$,
   it is possible to determine whether or not $x$ is a member of $A$.
** set
   a class $A$ is defined to be a set iff exists a class $B$ and $A\in B$.
** axiom of extensionality
   $[x\in A \iff x\in B] \to A = B$
** axiom of class formation
   for any statements $P(y)$ in the first-order predicate calculus
   involving a variable $y$, there exists a class $A$ such that 
   $x\in A$ if and only if $x$ is a set and the statement $P(x)$.
   we denote this class $A$ by $\{x|P(x)\}$.
** axiom of operation
   for union, intersection, functions, relations, Cartesian products,
   if one of these operation is performed on a set, then the result 
   is also a set.
** power axiom
   for all set $A$, the class $P(A)$ of all subsets of $A$ is itself a set.
   $P(A)$ is called the power set of $A$.
** subclass
   $A, B$ are classes, then
   $A\subset B \iff (\forall x\in A) x\in A \to x\in B$
   $A$ is a subclass of $B$.
   if $B$ is a set, then $A$ is a subset.
** empty set
   $\emptyset$
** family of set
   a family of sets indexed by $I$ is a collection of sets $A_i$.
** disjoint set
   $A\cap B = \emptyset$.

* Function 
** preliminary for funcion
   @page[3]
** $f$ and $g$ injective $\to$ $gf$ is injective
   proof: $x\not=y \to f(x)\not=f(y) \to g(f(x))\not= g(f(y))$
** $f:A\to B$ and $g:B\to C$ surjective $\to$ $gf$ is surjective
   proof: $f(A) = f(B) \to g(f(A)) = g(B) = C$.
** $gf$ injective $\to$ $f$ is injective
   proof: assume $f$ is not injective, then $(\exists x)(\exists y) f(x) = f(y)$.
   so $g(f(x)) = g(f(y))$. so $gf$ is not injective, contradiction.
** $gf$ surjective \to $g$ is surjective
   proof: assume $g$ is not surjective, then it is easy to see
   that $gf$ is not surjective, contradiction.
* Integer
** Theorem for gcd
   If $a_1, a_2, \cdots, a_n$ are integers, not all $0$, then $(a_1, a_2, \cdots, a_n)$ exists.
   Futhermore, there are integers $k_1, k_2, \cdots, k_n$ such that:
   \[(a_1, a_2, \cdots, a_n) = k_1a_1 + k_2a_2 + \cdots + k_na_n\].
*** proof:
	Let $S = \{x_1a_1 + x_2a_2 + \cdots + x_na_n | x_i\in Z, \sum_{i}x_ia_i > 0\}$.
	It is easy to see that $S\not=\emptyset$.
	Let $c = \sum_{i} x_ia_i$ be the least number in $S$.
	We claim that:
		1. $c | a_i$ for $1 \leq i \leq n$.
		2. $d\in Z$ and $d|a_1$ for $1\leq i\leq n$ $\to$ $d|c$.
	Then $c$ is obviously a gcd for $\{a_i\}$.

	- claim 1: $c | a_i$ for $1 \leq i \leq n$.
	   Assume $\exists o$ such that $c\nmid a_o$.
	   Then, $\exists q, k$ such that $a_o = q\sum_{i}x_ia_i + k$.
	   $a_o - q\sum_{i}x_ia_i = k > 0$.
	   $(1-qx_o)a_o + \sum_{i\not=o}x_ia_i = k > 0 \Rightarrow k\in S$.
	   And because $k < c$, we get a contradiction. $\square$
	- claim 2: $d\in Z$ and $d|a_1$ for $1\leq i\leq n$ $\to$ $d|c$.
	  $\forall d$ that devided $\{a_i\}$, we have $a_i = k_id, i = 1, 2, \cdots, n$.
	  Then $c = \sum_{i}x_ia_i = \sum_{i}x_ik_id = d\sum_{i}x_ik_i$.
	  So $d | c$. $\square$
* Axiom of choice
** axiom of choice
   The product of family of nonempty sets indexed by a nonempty set is nonempty.
** zorn's lemma
   If $A$ is a nonempty partially ordered set such that every chain in $A$ has
   upper bound in $A$, then $A$ contains a maximal element.
   [[https://en.wikipedia.org/wiki/Zorn%27s_lemma][zorn's lemma wiki]]
** ordinal number
   the number of all the ordinal's is more than the number of element in any sets.
*** Definition of the ordinal number
	1. $\emptyset$
	2. $\{\emptyset\}$
	3. $\{\emptyset, \{\emptyset\}\}$
    4. $\{\emptyset, \{\emptyset\}, \{\emptyset, \{\emptyset\}\}\}$
	5. $\cdots$
	according to the definition of the ordinal number.
	if there is a set $M$ which contains all the ordinal numbers,
	then we have $M\in M$, this is a paradox for a sets.
	I think things like $M\in M$ may happen on proper class.
	[[https://math.stackexchange.com/questions/1046863/how-can-a-set-contain-itself][here on stackexchange]] is a discussion for this issue.
** exercise 1 (p14)
   - for all subset $\{a, b\}\subset P(S)$. the g.l.b. is $a\cap b$.
	 the l.u.b. is $a\cup b$. and the unique maximal element is $S$.
   - $\{a\leq b, c\leq d\}$. 
	 the sub set $\{a, c\}$ do not have lower bound or upper bound.
   - partially set $\{a\leq b, c\leq d\}$ has no maximal elements.
	 partially set $\{a\leq b, c\leq d, a\leq d, c\leq b\}$ has maximal elements $b, d$.
** exercise 2 (p15)
   $A$ is a complte lattice $\Rightarrow$ there is a g.l.b. and l.u.b. for $A\in A$.
   from the antisymmetric property of $A$, we know that $A$ has 
   a unique maximal element and a unique minimal element.
   we denote the maximal element of $A$ by $m$.
   then it is easy to see that $m = f(m)$.
** exercise 3 (p15)
   $\underbrace{\frac{1}{1}}_{2}, \underbrace{\frac{1}{2}, \frac{2}{1}}_{3}, \underbrace{\frac{1}{3}, \frac{2}{2}, \frac{3}{1}}_{4}, \cdots$
** exercise 4 (p15)
   we need to prove that:
   	   the axiom of choice $\iff$ every set $S$ has a choice function.
*** proof: 
	$\Rightarrow$: we could construct a product on $P(S)\setminus \emptyset$.
	from axiom of choice, the result of this product is not empty.
	So, $\exists f \in \prod_{A\in S} A$ and we have $f(A)\in A$.
	obviously, $f$ is the choice function for $S$.
	$\Leftarrow$: Let $\{A_i|i\in I\}$ be any family, such that $(\forall i) A_i \not= \emptyset$.
	every set $S\not=\emptyset$ has a choice function $\Rightarrow$ $(\forall i) A_i$ has a choice function $f_i$.
	from these choice function $f_i$, we could then construct another function $\varphi$, 
	by defining $\varphi(i) = f_i(A_i)$. it is quite clear that $\varphi \in \prod_{i\in I} A_i$, 
	which is a nonempty set.
** exercise 5 (P15)
   $(\forall x\in R) (x, 0)$ is the maximal element in $S$.
   thus, $S$ has infinitely many maximal elements.
** exercise 6 (P15)
   from exercise 4, we know that $(\forall i) A_i$ has a choice functon $f$,
   mapping all the subsets $B$ of $A_i$ to an element in $B$.
   once we have the function $f$, we could simpliy enumerate $f(A_i)$ over
   all the elements in $A_i$ ...
** exercise 7 (P15)
   There are only 2 cases in which one element $a\in A$ does not have an
   immediate successor:
   1. $\{x\in A| a < x\} = \emptyset$.
   2. $\{x\in A| a < x\}$ does not have a least element.
*** $A$ is well-ordered
	under this condition, only the first case could happen.
	assume that we have 2 elements $a, b$ in $A$ that has no immediate successor.
	however, $A$ is well-ordered, so there must be a least element in $\{a, b\}$.
	assuming that the least element is $a$, we will find that the set $\{x\in A| a < x\}$ is not empty.
	which means that $a$ has a immediate successor in $A$, which is a contradiction.
*** $A$ is a linearly ordered set
	$\{10, \cdots, -1, 0, 1, 2, 3, 4, 5\}$.
	we set that $10 \leq \cdots \leq -1 \leq 0 \leq 2 \leq 3 \leq 4 \leq 5$.
	then, $10, 5$ are 2 elements with no immediate successor.
* Cardinal numbers
** If $A$ is a set and $P(A)$ its power set, then $|A| < |P(A)|$
*** proof
	to finish the proof, we claim that:
	1. $|A| \leq |P(A)|$
	2. $|A| \not= |P(A)|$
	we prove them one by one.
	1. $|A| \leq |P(A)|$:
	   define a map $f: A\to P(A)$ as $a\mapsto \{a\}$.
	   this map is obviously a injection. so $|A| \leq |P(A)|$.
	2. $|A| \not= |P(A)|$:
	   to prove this, we only need to prove that:
	   $[(\forall) f: A\to P(A)] \to f \mbox{is not surjective}$.
	   for any function $f$, we define a set $B = \{a\in A | a\not\in f(a)\}$.
	   it is easy to see that by definition, $B\subset A$.
	   so, if $f$ is surjective, then $(\exists) x\in A \land x\mapsto B$.
	   then we could get $x\in B \land x\not\in B$, which is a contradiction.
** ordered by extension (p18)
** Exercise 1 (P21)
   1. (a) omit
   2. (b) (a) $\Rightarrow$ (b)
   3. (c) omit
** Exercise 2 (P21)
   1. Assume that we have a infinit set $A = \{a_0, a_1, a_2, \cdots \}$.
      Then we could build a bijection $f: A\to A-\{a_0\}$ by setting $f(a_i) = a_{i+1}, i\in N$.
      It is easy to see that $A-\{a_0\}\subset A$.
   2. $\Leftarrow$: could be easily got from (1).
      $\Rightarrow$: could be got from 1.(1).

#+OPTIONS: LaTeX:verbatim
** Exercise 3 (P21)
   1. we could build a bijection $f: Z\to N$ by setting:
      \begin{displaymath}
        f(x) = \left\{
        \begin{array}{lr}
            0, &x = 0 \\
            -x*2, &x < 0 \\
            x*2+1, &x > 0
        \end{array}
        \right. 
      \end{displaymath}
   2. omit.
** Exercise 4, 5, 6, 7, 8 (P21)
   omit.
** Exercise 9 (P21)
