#+SETUPFILE: https://fniessen.github.io/org-html-themes/setup/theme-readtheorg.setup
* What is vertex packing problem (VP)
  The traditional vertex packing problem deﬁned on an
  undirected graph identiﬁes the largest weighted independent
  set of nodes, that is, a set of nodes whose induced subgraph 
  contains no edges.
* The generalized vertex packing problem (GVP-k) that this article cares about
  k edges may exist within the subgraph induced by the chosen set of nodes.
* Some application
  A particular context in which such problems arise is in the national 
  airspace planning model
* Introduction
  G = (N, E), weighted c_j, for j = 1, \cdots, n.
** Integer Programming Model (for VP)
  \begin{align*}
	  \mbox{Maximize: } & cx \\
	  \mbox{Subject to: } & Ax \leq e \\
				  & x \in \{0, 1\}
  \end{align*}
  1) A is a p \times n matrix a_{hi} = 1 means vertex i \in edge h
  2) e is a all-one vector.
  3) \Rightarrow Ax \leq e means that each edges 2 end-points should not
	 be in the answer x simutaneously.
** Prefect Graph
   chromatic number = maximum clique cardinality (for each G' \(\subseteq\) G)
** Integer Programming Model (for GVP-k)
   \begin{align*}
	\mbox{Maximize: } & cx \\
	\mbox{Subject to: } & \sum_{(i,j) \in E} z_{ij} \leq k \\
	& z_{ij} \geq x_i + x_j - 1, z_{ij} \geq 0 \\
	& x_j \in \{0, 1\}, \forall j \in N
   \end{align*}
   note that edge (i, j) is in the answer when $z_{ij} = 1 = x_ix_j$
* DONE Facets and partial convex hull representations for GVP-k
  CLOSED: [2019-01-23 Wed 01:50] SCHEDULED: <2019-01-22 Tue 19:00>
  *Proposition 1*: Consider a graph G and a subgraph $\hat{G}$ of G. 
  If Dx \leq d represents a set of valid inequalities for GVP-k deﬁned on $\hat{G}$, 
  then Dx \leq d is valid for GVP-k deﬁned on G. 

  *Proof*: Since GVP-k for $\hat{G}$ is a relaxation of GVP-k deﬁned on G, 
  the _restrictions_ that govern a feasible generalized vertex packing
  solution on $\hat{G}$ are a subset of those valid for G. This completes the proof.

  *Note*: You could use less restrictions on $\hat{G}$ than on G (maybe a subset).
  

